export const mockUsers = [
  {
    id: 3108587,
    first_name: 'Marat',
    last_name: 'Sadriev',
    email: 'marat.sadriev@flatstack.com',
    telephone: '',
    timezone: 'Moscow',
    weekly_capacity: 144000,
    has_access_to_all_future_projects: false,
    is_contractor: false,
    is_admin: false,
    is_project_manager: false,
    can_see_rates: false,
    can_create_projects: false,
    can_create_invoices: false,
    is_active: true,
    calendar_integration_enabled: false,
    calendar_integration_source: null,
    created_at: '2020-01-17T15:24:04Z',
    updated_at: '2020-08-31T11:02:48Z',
    default_hourly_rate: 0,
    cost_rate: 0,
    roles: ['Front-end'],
    avatar_url: 'https://d3s3969qhosaug.cloudfront.net/default-avatars/4d53.png?1579274644',
  },
  {
    id: 3056970,
    first_name: 'Shakhriddin',
    last_name: 'Ishmukhamedov',
    email: 'shakhriddin.ishmukhamedov@flatstack.com',
    telephone: '',
    timezone: 'Moscow',
    weekly_capacity: 144000,
    has_access_to_all_future_projects: false,
    is_contractor: false,
    is_admin: false,
    is_project_manager: false,
    can_see_rates: false,
    can_create_projects: false,
    can_create_invoices: false,
    is_active: false,
    calendar_integration_enabled: false,
    calendar_integration_source: null,
    created_at: '2019-12-02T12:01:05Z',
    updated_at: '2020-03-03T16:06:43Z',
    default_hourly_rate: 0,
    cost_rate: 0,
    roles: ['Front-end', 'Senior'],
    avatar_url:
      'https://proxy.harvestfiles.com/production_harvestapp_public/uploads/users/avatar/003/056/970/3902daafe554f829f9825b686316aa846a32f017/normal.?1575288705',
  },
  {
    id: 2902332,
    first_name: 'Rustem',
    last_name: 'Giniyatullin',
    email: 'rustem.giniyatullin@flatstack.com',
    telephone: '',
    timezone: 'Moscow',
    weekly_capacity: 144000,
    has_access_to_all_future_projects: false,
    is_contractor: false,
    is_admin: true,
    is_project_manager: false,
    can_see_rates: true,
    can_create_projects: true,
    can_create_invoices: true,
    is_active: true,
    calendar_integration_enabled: true,
    calendar_integration_source: 'google',
    created_at: '2019-07-26T15:25:34Z',
    updated_at: '2020-08-31T12:02:09Z',
    default_hourly_rate: 0,
    cost_rate: 0,
    roles: ['Design & UX'],
    avatar_url:
      'https://proxy.harvestfiles.com/production_harvestapp_public/uploads/users/avatar/002/902/332/5d791143266d015ac83b3c537c2d9334610f87a6/normal.?1564155027',
  },
  {
    id: 2902328,
    first_name: 'Renas',
    last_name: 'Sitdikov',
    email: 'renas.sitdikov@flatstack.com',
    telephone: '',
    timezone: 'Moscow',
    weekly_capacity: 144000,
    has_access_to_all_future_projects: false,
    is_contractor: false,
    is_admin: true,
    is_project_manager: false,
    can_see_rates: true,
    can_create_projects: true,
    can_create_invoices: true,
    is_active: true,
    calendar_integration_enabled: false,
    calendar_integration_source: null,
    created_at: '2019-07-26T15:25:32Z',
    updated_at: '2020-08-31T09:47:07Z',
    default_hourly_rate: 0,
    cost_rate: 0,
    roles: ['Front-end'],
    avatar_url:
      'https://proxy.harvestfiles.com/production_harvestapp_public/uploads/users/avatar/002/902/328/ee1e2f89ddc1c7a2bd5252d4b1324de5015709d4/normal.jpg?1577303947',
  },
  {
    id: 1403136,
    first_name: 'Timur',
    last_name: 'Vafin',
    email: 'timur.vafin@flatstack.com',
    telephone: '',
    timezone: 'Moscow',
    weekly_capacity: 0,
    has_access_to_all_future_projects: false,
    is_contractor: false,
    is_admin: true,
    is_project_manager: false,
    can_see_rates: true,
    can_create_projects: true,
    can_create_invoices: true,
    is_active: true,
    calendar_integration_enabled: true,
    calendar_integration_source: 'google',
    created_at: '2016-09-27T12:41:51Z',
    updated_at: '2020-05-15T14:11:22Z',
    default_hourly_rate: 0,
    cost_rate: 0,
    roles: ['Advisor'],
    avatar_url:
      'https://proxy.harvestfiles.com/production_harvestapp_public/uploads/users/avatar/001/403/136/8253a73f50a715581a40eb3f431d133b6e6325af/normal.png?1474982519',
  },
];
