export const mockTeamReport = [
  {
    user_id: 3108587,
    user_name: 'Marat Sadriev',
    is_contractor: false,
    total_hours: 40,
    billable_hours: 34,
    currency: 'USD',
    billable_amount: 0,
  },
  {
    user_id: 2902328,
    user_name: 'Renas Sitdikov',
    is_contractor: false,
    total_hours: 41.5,
    billable_hours: 33,
    currency: 'USD',
    billable_amount: 0,
  },
  {
    user_id: 2902332,
    user_name: 'Rustem Giniyatullin',
    is_contractor: false,
    total_hours: 10.5,
    billable_hours: 10.5,
    currency: 'RUB',
    billable_amount: 0,
  },
  {
    user_id: 2902332,
    user_name: 'Rustem Giniyatullin',
    is_contractor: false,
    total_hours: 29.5,
    billable_hours: 24.5,
    currency: 'USD',
    billable_amount: 80,
  },
];
